-- 1. สร้างตาราง Owner
CREATE TABLE IF NOT EXISTS "Owner" (
    "owner_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "first_name" VARCHAR(60) NOT NULL,
    "last_name" VARCHAR(60) NOT NULL,
    "subdistrict" VARCHAR(60) NOT NULL,
    "district" VARCHAR(60) NOT NULL,
    "province" VARCHAR(60) NOT NULL,
    PRIMARY KEY("owner_id")
);

-- 2. สร้างตาราง Owner_phone
CREATE TABLE IF NOT EXISTS "Owner_phone" (
    "phone_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "owner_id" INTEGER NOT NULL,
    "phone_number" VARCHAR(255) NOT NULL,
    PRIMARY KEY("phone_id"),
    FOREIGN KEY("owner_id") REFERENCES "Owner"("owner_id") ON DELETE CASCADE
);

-- 3. สร้างตาราง Pet
CREATE TABLE IF NOT EXISTS "Pet" (
    "pet_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "pet_name" VARCHAR(60) NOT NULL,
    "birth_date" DATE NOT NULL,
    "owner_id" INTEGER NOT NULL,
    PRIMARY KEY("pet_id"),
    FOREIGN KEY("owner_id") REFERENCES "Owner"("owner_id") ON DELETE CASCADE
);

-- 4. สร้างตาราง Vet
CREATE TABLE IF NOT EXISTS "Vet" (
    "vet_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "vet_name" VARCHAR(60) NOT NULL,
    PRIMARY KEY("vet_id")
);

-- 5. สร้างตาราง Vet_Specialty
CREATE TABLE IF NOT EXISTS "Vet_Specialty" (
    "specialty_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "vet_id" INTEGER NOT NULL,
    "specialty_name" VARCHAR(120),
    PRIMARY KEY("specialty_id"),
    FOREIGN KEY("vet_id") REFERENCES "Vet"("vet_id") ON DELETE CASCADE
);

-- 6. สร้างตาราง Visit (Weak Entity)
CREATE TABLE IF NOT EXISTS "Visit" (
    "pet_id" INTEGER NOT NULL, 
    "visit_no" INTEGER NOT NULL CHECK ("visit_no" > 0), -- เพิ่ม CHECK บังคับครั้งที่เข้าตรวจต้องมากกว่า 0
    "visit_date" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, -- เพิ่ม DEFAULT ตามโจทย์
    "vet_id" INTEGER NOT NULL,
    PRIMARY KEY("pet_id", "visit_no"),
    FOREIGN KEY("pet_id") REFERENCES "Pet"("pet_id") ON DELETE CASCADE,
    FOREIGN KEY("vet_id") REFERENCES "Vet"("vet_id")
);

-- 7. สร้างตาราง Medicine
CREATE TABLE IF NOT EXISTS "Medicine" (
    "med_id" INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" VARCHAR(120) NOT NULL UNIQUE, -- มี UNIQUE ตามโจทย์
    "unit_price" DECIMAL NOT NULL CHECK ("unit_price" >= 0),
    PRIMARY KEY("med_id")
);

-- 8. สร้างตาราง Prescription (M:N)
CREATE TABLE IF NOT EXISTS "Prescription" (
    "pet_id" INTEGER NOT NULL, 
    "visit_no" INTEGER NOT NULL,
    "med_id" INTEGER NOT NULL,
    "dosage" VARCHAR(255) NOT NULL,
    "days" INTEGER NOT NULL CHECK ("days" > 0), -- เพิ่ม CHECK จำนวนวันต้องมากกว่า 0
    "billed_price" DECIMAL NOT NULL CHECK ("billed_price" >= 0), 
    PRIMARY KEY("pet_id", "visit_no", "med_id"),
    FOREIGN KEY("pet_id", "visit_no") REFERENCES "Visit"("pet_id", "visit_no") ON DELETE CASCADE, -- Composite FK
    FOREIGN KEY("med_id") REFERENCES "Medicine"("med_id")
);